Repository samirm00/restaurants-finder, pull requests merged in 2021-03, with the labels that each got.

#14 added index.html, bootstrap, font-awesome
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/routes/Home.js
  client/src/routes/RestaurantDetailPage.js
  client/src/routes/UpdatePage.js
Labels: client

#15 added components folder/AddRestaurants.js,HEader.js, ReastaurantList.js
  client/src/components/AddRestaurant.js
  client/src/components/Header.js
  client/src/components/RestaurantList.js
  client/src/routes/Home.js
Labels: component

#16 create a server
  server.js
Labels: new branch, pull request

#17 create routes with controllers
  .gitignore
  api/controllers.js
  api/routes.js
  config/default.js
  config/development.js
  config/index.js
  config/production.js
  db/index.js
  package-lock.json
  package.json
Labels: new branch, pull request

#18 CRUD for restaurants and reviews
  api/controllers.js
  api/routes.js
  client/src/api/RestaurantFinder.js
  client/src/components/AddRestaurant.js
  client/src/components/AddReview.js
  client/src/components/RestaurantList.js
  client/src/components/Reviews.js
  client/src/components/StarRating.js
  client/src/components/UpdateRestaurant.js
  client/src/context /RestaurantsContext.js
  client/src/routes/RestaurantDetailPage.js
  client/src/routes/UpdatePage.js
Labels: new branch, pull request

#22 added rating to components/RestaurantList.js and routes/RestaurantDet…
  client/src/components/RestaurantList.js
  client/src/routes/RestaurantDetailPage.js
Labels: client
